plugins {
    id "com.android.application"
}

android {
    namespace "com.amortom.bk7258converter"
    compileSdk 35

    defaultConfig {
        applicationId "com.amortom.bk7258converter"
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName "0.1.4"
    }

    flavorDimensions += "abi"
    productFlavors {
        arm64 {
            dimension "abi"
            versionNameSuffix "-arm64"
            ndk {
                abiFilters "arm64-v8a"
            }
        }

        x64 {
            dimension "abi"
            versionNameSuffix "-x64"
            ndk {
                abiFilters "x86_64"
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "io.github.jamaismagic.ffmpeg:ffmpeg-kit-main-min-16kb:6.1.4"
}
